apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: final
data:
  STUDENT_NAME: "Winlyn, Heracleo, Vernard"
  S3_BUCKET: "clo835-finalproject-whv " # Replace with your bucket name
  S3_IMAGE_NAME: "whv-image.jpg"  # Replace with your image file name