apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: final
data:
  APP_COLOR: "Green"
  AWS_REGION: "us-east-1"
  GROUP_NAME: "Group 11"
  STUDENT_NAME: "Winlyn Luena, Vernard Canlas, Heracleo Elbina"
  S3_BUCKET: "clo835-finalproject-whv"
  S3_IMAGE_NAME: "whv-image.jpg"
  DBHOST: "mysql" # Matches the Service name below
  DBPORT: "3306"
  DATABASE: "employees"