apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        version: "v6-s3-bg"
    spec:
      serviceAccountName: clo835
      containers:
      - name: flask-app
        image: 832666763937.dkr.ecr.us-east-1.amazonaws.com/final-project-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        env:
        # STUDENT NAME for the Header
        - name: STUDENT_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: STUDENT_NAME
        # S3 CONFIGURATION (handles background image)
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: S3_BUCKET
        - name: S3_IMAGE_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: S3_IMAGE_NAME
        # DATABASE CREDENTIALS (Secrets)
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: db-password
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: db-user
        # DATABASE CONNECTION INFO (ConfigMap)
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DBHOST
        - name: DBPORT
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DBPORT
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DATABASE