apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: final
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None  # This makes it a Headless Service, common for DBs