apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets # Match the name in Flask & MySQL deployments
  namespace: final
type: Opaque
stringData:
  db-user: "root"      # Matches the 'key: db-user' in deployment
  db-password: "pw"    # Matches the 'key: db-password' in deployment