apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: final
type: Opaque
data:
  # Replace these with your Base64 encoded strings
  db-user: cm9vdA== 
  db-password: WW91clNlY3JldFBhc3N3b3Jk